### ISSUE TITLE
Quorum-Wizard support for windows

### ISSUE THREAD

**Issue by technicaldwiti** [jpmorganchase/quorum-remix#61] opened 2020-06-21 12:35 UTC
Quorum doesn't work generally on Windows because it uses unix sockets heavily, which don't have full support (even in Windows Subsystem for Linux). Therefore the Wizard also doesn't support Windows right now.

**Comment by bmcd87** [comment] 2020-06-21 15:27
Duplicate of https://github.com/jpmorganchase/quorum-wizard/issues/63

**Closed by bmcd87** 2020-06-21 15:27 UTC
